<?php
$DbPath="../databases/webdbfr.mdb";

$user='dcstecgr_artcomu';
$password='artcom2015artcom';
$DbName="webdbfr.mdb";
$ArtHomeLimit=4;
$AdminSidTimeOut=120;
$SubRubActive=true;
$AppDeName="Dream CMS";
$AppVersion="1.2";
$AppEngine="PHP";
$AppClientHTML="<font size=\"2\">BackOffice d'Administration du site web <b> ARTCOM (FR)</b></font>";
$AppCopyHTML="(c) Artcom International 2013";
$WYSIWYGMode=true;
$DeBaseURL="http://www.artcom.com.tn";
$DeWebVirtualPath="../../www/fr/";
$DeImageVirtualPath="../images";
$DeDefaultDir="LTR";
$DeDefaultFont="Verdana";
$DeDefaultFontSize="8pt";
$AdminscrTimeOut=300;
$showHiddenItems=true;
$calculateTotalSize=true;
$calculateFolderSize=true;
$AllowedExt=".jpg;.jpeg;.gif;.png;.wma;.wmv;.swf";
$ExtImage="icons/jpgicon.gif;icons/jpgicon.gif;icons/gificon.gif;icons/pngicon.gif;icons/wmaicon.gif;icons/wmvicon.gif;icons/swficon.gif";
$displayPath=false;
                 
?>